app/Http/routes.php
<?php

use Cmgmyr\Messenger\Models\Message;
use Intervention\Image\Facades\Image;

/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/

Route::get('/contact', 'PageController@contact');
Route::post('/contact', 'PageController@saveContact');

Route::group(['prefix' => 'api', 'middleware' => ['auth', 'cors'], 'namespace' => 'API'], function () {
    Route::group(['prefix' => 'v1'], function () {
        require config('infyom.laravel_generator.path.api_routes');
    });
});

Route::post('pusher/auth', function (Illuminate\Http\Request $request, Pusher $pusher) {
    return $pusher->presence_auth(
        $request->input('channel_name'),
        $request->input('socket_id'),
        uniqid(),
        ['username' => $request->input('username')]
    );
});


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::resource('timelines', 'TimelineController');

Route::group(['middleware' => ['web']], function () {
    Route::auth();
});


// Redirect to facebook to authenticate
Route::get('facebook', 'Auth\AuthController@facebookRedirect');
// Get back to redirect url
Route::get('account/facebook', 'Auth\AuthController@facebook');

// Redirect to google to authenticate
Route::get('google', 'Auth\AuthController@googleRedirect');
// Get back to redirect url
Route::get('account/google', 'Auth\AuthController@google');

// Redirect to twitter to authenticate
Route::get('twitter', 'Auth\AuthController@twitterRedirect');
// Get back to redirect url
Route::get('account/twitter', 'Auth\AuthController@twitter');

// Redirect to linkedin to authenticate
Route::get('linkedin', 'Auth\AuthController@linkedinRedirect');
// Get back to redirect url
Route::get('account/linkedin', 'Auth\AuthController@linkedin');


// Login
Route::get('/login', 'Auth\AuthController@getLogin');
Route::post('/login', 'Auth\AuthController@login');

// Register
Route::get('/register', 'Auth\AuthController@register');

Route::post('/register', 'Auth\AuthController@registerUser');

Route::get('email/verify', 'Auth\AuthController@verifyEmail');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/', 'TimelineController@showFeed');
    Route::get('/browse', 'TimelineController@showGlobalFeed');
    Route::get('/deactivate-home', 'TimelineController@deactivateHome');
});


Route::get('/home', 'HomeController@index');

Route::post('/member/update-role', 'TimelineController@assignMemberRole');
Route::post('/member/updatepage-role', 'TimelineController@assignPageMemberRole');
Route::get('/post/{post_id}', 'TimelineController@singlePost');

Route::get('/poost/{post_id}', 'TimelineController@postshareframe');
/*
|--------------------------------------------------------------------------
| Admin routes
|--------------------------------------------------------------------------
*/


Route::group(['prefix' => '/admin', 'middleware' => ['auth', 'role:admin']], function () {
    Route::get('/', 'AdminController@dashboard');
    Route::get('/general-settings', 'AdminController@generalSettings');
    Route::post('/general-settings', 'AdminController@updateGeneralSettings');

    Route::get('/user-settings', 'AdminController@userSettings');
    Route::post('/user-settings', 'AdminController@updateUserSettings');

    Route::get('/page-settings', 'AdminController@pageSettings');
    Route::post('/page-settings', 'AdminController@updatePageSettings');

    Route::get('/group-settings', 'AdminController@groupSettings');
    Route::post('/group-settings', 'AdminController@updateGroupSettings');

    Route::get('/custom-pages', 'AdminController@listCustomPages');
    Route::get('/custom-pages/create', 'AdminController@createCustomPage');
    Route::post('/custom-pages', 'AdminController@addCustomPage');
    Route::get('/custom-pages/{id}/edit', 'AdminController@editCustomPage');
    Route::post('/custom-pages/{id}/update', 'AdminController@updateCustomPage');

    Route::get('/announcements', 'AdminController@getAnnouncements');
    Route::get('/announcements/create', 'AdminController@createAnnouncement');
    Route::get('/announcements/create_business', 'AdminController@createBusinessAnnouncement');
    Route::get('/announcements/create_art', 'AdminController@createArtAnnouncement');
    Route::get('/announcements/create_it', 'AdminController@createITAnnouncement');
    Route::get('/announcements/create_medicine', 'AdminController@createMedicineAnnouncement');
    Route::get('/announcements/create_eng', 'AdminController@createEngineeringAnnouncement');
    Route::get('/announcements/create_english', 'AdminController@createEnglishAnnouncement');
    Route::get('/announcements/create_std', 'AdminController@createStudentAnnouncement');
    Route::get('/announcements/{id}/edit', 'AdminController@editAnnouncement');
    Route::post('/announcements/{id}/update', 'AdminController@updateAnnouncement');
    Route::post('/announcements', 'AdminController@addAnnouncements');
    Route::get('/activate/{announcement_id}', 'AdminController@activeAnnouncement');
    Route::get('/inactivate/{announcement_id}', 'AdminController@inactiveAnnouncement');

    Route::get('/themes', 'AdminController@themes');
    Route::get('/change-theme/{name}', 'AdminController@changeTheme');

    Route::get('/users', 'AdminController@showUsers');
    Route::get('/users/show', 'AdminController@showDeactivateUsers');
    Route::get('/users/add/create', 'AdminController@createUser');
    Route::get('/users/add/create_admin', 'AdminController@createAdmin');
    Route::get('/users/{username}/edit', 'AdminController@editUser');
    Route::post('/users/{username}/edit', 'AdminController@updateUser');
    Route::post('/users', 'AdminController@addUsers');
    Route::post('/users/add-admin', 'AdminController@addAdmin');
    Route::get('/users/{user_id}/delete', 'AdminController@deleteUser');
    Route::get('/activate-user/{user_id}', 'AdminController@activateUser');
    Route::get('/deactivate-user/{user_id}', 'AdminController@deactivateUser');

    Route::get('/requests', 'AdminController@show_req');
    Route::get('/requests/{user_id}/approve', 'AdminController@approveUser');
    Route::get('/requests/{user_id}/reject', 'AdminController@rejectUser');


    Route::get('/users/{username}/delete', 'AdminController@deleteUser');
    Route::post('/users/{username}/newpassword', 'AdminController@updatePassword');

    Route::get('/pages', 'AdminController@showPages');
    Route::get('/pages/add/create', 'AdminController@createPage');
    Route::post('/pages', 'AdminController@addPage');
    Route::get('/pages/{username}/edit', 'AdminController@editPage');
    Route::post('/pages/{username}/edit', 'AdminController@updatePage');
    Route::get('/pages/{page_id}/delete', 'AdminController@deletePage');


    Route::get('/groups', 'AdminController@showGroups');
    Route::get('/groups/{username}/edit', 'AdminController@editGroup');
    Route::post('/groups/{username}/edit', 'AdminController@updateGroup');
    Route::get('/groups/{group_id}/delete', 'AdminController@deleteGroup');


    //Route::get('/blocks', 'AdminController@getAnnouncements');
    Route::get('/blocks/{id}/create', 'AdminController@createBlock');
    Route::get('/blocks/{id}/edit', 'AdminController@editBlock');
    Route::post('/blocks/{id}/update', 'AdminController@updateBlock');
    Route::post('/blocks', 'AdminController@addBlocks');
    Route::get('/blocks/{block_id}/{report_id}/delete', 'AdminController@removeBlock');


    Route::get('/manage-reports', 'AdminController@manageReports');
    Route::post('/manage-reports', 'AdminController@updateManageReports');
    Route::get('/mark-safe/{report_id}', 'AdminController@markSafeReports');
    Route::get('/delete-post/{report_id}/{post_id}', 'AdminController@deletePostReports');

    Route::get('/manage-ads', 'AdminController@manageAds');
    Route::get('/update-database', 'AdminController@getUpdateDatabase');
    Route::post('/update-database', 'AdminController@postUpdateDatabase');
    Route::get('/get-env', 'AdminController@getEnv');
    Route::post('/save-env', 'AdminController@saveEnv');
    Route::post('/manage-ads', 'AdminController@updateManageAds');
    Route::get('/settings', 'AdminController@settings');
    Route::get('/markpage-safe/{report_id}', 'AdminController@markPageSafeReports');
    Route::get('/deletepage-post/{report_id}/{timeline_id}', 'AdminController@deletePageReports');
    Route::get('/deleteuser-post/{report_id}/{timeline_id}', 'AdminController@deleteUserReports');
    Route::get('/deletegroup-post/{report_id}/{timeline_id}', 'AdminController@deleteGroupReports');
});



Route::group(['prefix' => '/devloper', 'middleware' => ['auth', 'role:devloper']], function () {
    Route::get('/', 'DevController@dashboard');
    Route::get('/general-settings', 'DevController@generalSettings');
    Route::post('/general-settings', 'DevController@updateGeneralSettings');

    Route::get('/user-settings', 'DevController@userSettings');
    Route::post('/user-settings', 'DevController@updateUserSettings');

    Route::get('/page-settings', 'DevController@pageSettings');
    Route::post('/page-settings', 'DevController@updatePageSettings');

    Route::get('/group-settings', 'DevController@groupSettings');
    Route::post('/group-settings', 'DevController@updateGroupSettings');

    Route::get('/custom-pages', 'DevController@listCustomPages');
    Route::get('/custom-pages/create', 'DevController@createCustomPage');
    Route::post('/custom-pages', 'DevController@addCustomPage');

app/Timeline.php
<?php

namespace App;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="Timeline",
 *      required={},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="username",
 *          description="username",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="name",
 *          description="name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="about",
 *          description="about",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="avatar_id",
 *          description="avatar_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="cover_id",
 *          description="cover_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="cover_position",
 *          description="cover_position",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="type",
 *          description="type",
 *          type="string"
 *      )
 * )
 */
class Timeline extends Model
{
    use SoftDeletes;

    public $table = 'timelines';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'username',
        'name',
        'about',
        'avatar_id',
        'cover_id',
        'cover_position',
        'type',
        'deleted_at',
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id'             => 'integer',
        'username'       => 'string',
        'name'           => 'string',
        'about'          => 'string',
        'avatar_id'      => 'integer',
        'cover_id'       => 'integer',
        'cover_position' => 'string',
        'type'           => 'string',
        'deleted_at'     => 'datetime',
    ];

    /**
     * Validation rules.
     *
     * @var array
     */
    public static $rules = [

    ];

    public function toArray()
    {
        $array = parent::toArray();

        $cover_url = $this->cover()->get()->toArray();
        $avatar_url = $this->avatar()->get()->toArray();


        $array['cover_url'] = $cover_url;
        $array['avatar_url'] = $avatar_url;


        if ($this->type == 'user') {
            $array['verified'] = $this->user()->first() ? $this->user()->first()->verified : 0;
        } else {
            $array['verified'] = $this->page()->first() ? $this->page()->first()->verified : 0;
        }

        return $array;
    }

    public function posts()
    {
        return $this->hasMany('App\Post');
    }

    public function user()
    {
        return $this->hasOne('App\User');
    }

    public function avatar()
    {
        return $this->belongsTo('App\Media', 'avatar_id');
    }

    public function cover()
    {
        return $this->belongsTo('App\Media', 'cover_id');
    }

    public function page()
    {
        return $this->hasOne('App\Page');
    }

    public function groups()
    {
        return $this->hasOne('App\Group');
    }

    public function reports()
    {
        return $this->belongsToMany('App\User', 'timeline_reports', 'timeline_id', 'reporter_id')->withPivot('status');
    }
}

resources/views/timelines/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <h1 class="pull-left">Create New Timeline</h1>
        </div>
    </div>

    @include('core-templates::common.errors')

    <div class="row">
        {!! Form::open(['route' => 'timelines.store']) !!}

            @include('timelines.fields')

        {!! Form::close() !!}
    </div>
@endsection

resources/views/timelines/edit.blade.php
@extends('layouts.app')

@section('content')
        <div class="row">
            <div class="col-sm-12">
                <h1 class="pull-left">Edit Timeline</h1>
            </div>
        </div>

        @include('core-templates::common.errors')

        <div class="row">
            {!! Form::model($timeline, ['route' => ['timelines.update', $timeline->id], 'method' => 'patch']) !!}

            @include('timelines.fields')

            {!! Form::close() !!}
        </div>
@endsection

resources/views/timelines/fields.blade.php
<!-- Username Field -->
<div class="form-group col-sm-6">
    {!! Form::label('username', 'Username:') !!}
    {!! Form::text('username', null, ['class' => 'form-control', 'disabled' => 'disabled']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- About Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('about', 'About:') !!}
    {!! Form::textarea('about', null, ['class' => 'form-control']) !!}
</div>

<!-- Avatar Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('avatar_id', 'Avatar Id:') !!}
    {!! Form::number('avatar_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Cover Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('cover_id', 'Cover Id:') !!}
    {!! Form::number('cover_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Cover Position Field -->
<div class="form-group col-sm-6">
    {!! Form::label('cover_position', 'Cover Position:') !!}
    {!! Form::text('cover_position', null, ['class' => 'form-control']) !!}
</div>

<!-- Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('type', 'Type:') !!}
    {!! Form::text('type', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('timelines.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/timelines/index.blade.php
@extends('layouts.app')

@section('content')
        <h1 class="pull-left">Timelines</h1>
        <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('timelines.create') !!}">Add New</a>

        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        @include('timelines.table')
        
@endsection

resources/views/timelines/show.blade.php
@extends('layouts.app')

@section('content')
    @include('timelines.show_fields')

    <div class="form-group">
           <a href="{!! route('timelines.index') !!}" class="btn btn-default">Back</a>
    </div>
@endsection

resources/views/timelines/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $timeline->id !!}</p>
</div>

<!-- Username Field -->
<div class="form-group">
    {!! Form::label('username', 'Username:') !!}
    <p>{!! $timeline->username !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $timeline->name !!}</p>
</div>

<!-- About Field -->
<div class="form-group">
    {!! Form::label('about', 'About:') !!}
    <p>{!! $timeline->about !!}</p>
</div>

<!-- Avatar Id Field -->
<div class="form-group">
    {!! Form::label('avatar_id', 'Avatar Id:') !!}
    <p>{!! $timeline->avatar_id !!}</p>
</div>

<!-- Cover Id Field -->
<div class="form-group">
    {!! Form::label('cover_id', 'Cover Id:') !!}
    <p>{!! $timeline->cover_id !!}</p>
</div>

<!-- Cover Position Field -->
<div class="form-group">
    {!! Form::label('cover_position', 'Cover Position:') !!}
    <p>{!! $timeline->cover_position !!}</p>
</div>

<!-- Type Field -->
<div class="form-group">
    {!! Form::label('type', 'Type:') !!}
    <p>{!! $timeline->type !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $timeline->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $timeline->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $timeline->deleted_at !!}</p>
</div>

resources/views/timelines/table.blade.php
<table class="table table-responsive" id="timelines-table">
    <thead>
        <th>Avatar Id</th>
        <th>Username</th>
        <th>Name</th>
        <th>About</th>
        <th>Type</th>
        <th>Created At</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($timelines as $timeline)
        <tr>
            <td>{!! $timeline->avatar_id !!}</td>
            <td>{!! $timeline->username !!}</td>
            <td>{!! $timeline->name !!}</td>
            <td>{!! $timeline->about !!}</td>
            <td>{!! $timeline->type !!}</td>
            <td>{!! $timeline->created_at !!}</td>
            <td>
                {!! Form::open(['route' => ['timelines.destroy', $timeline->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('timelines.show', [$timeline->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('timelines.edit', [$timeline->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>